### ISSUE TITLE
Distance sensor .relative_size() returns u32 when return value is i32

### ISSUE THREAD

**Issue by alexDickhans** [vexide/vexide#115]
## Bug Description
When .relative_size() is called it returns an 32-bit integer, not an unsigned int. When .relative_size() is called it returns a number that is very large on failures indicating the two's compliement wasn't respected. When it is changed to i32 it returns -1 upon .relative_size() failure. 

## Code to reproduce
```rust
#![no_main]
#![no_std]

use core::time::Duration;
use vexide::prelude::*;

#[vexide::main]
async fn main(peripherals: Peripherals) {

    let distance = DistanceSensor::new(peripherals.port_1);

    loop {
        println!("Relative Size: {}", distance.relative_size().unwrap_or_default());

        sleep(Duration::from_millis(10)).await;
    }
}
```

## Expected vs. actual behavior
It returns a very large number on a seemingly failure to acquire a size measurement but with i32 it returns -1. I would also expect this function to return an Optional to make this failure more explicit. 

## Additional information

I think that's it

**Comment by Gavin-Niederman** [comment]
If you can find any more of these that would be great. A lot of vex sdk functions return i32s and never return negative values so its easy to miss some of these.
