### ISSUE TITLE
Controller API sucks to use.

### ISSUE THREAD

**Issue by Tropix126** [vexide/vexide#131]
## Problem Description
Really not sure how else to put it - most of this is my fault. On paper it *seems* fine, but there is a lot of redundant error handling involved with the controller API as well as some other minor annoyances:
- Controller errors for a given timeslice cannot occur for one channel but not another, yet each getter returns its own `Result`, as if the operation could fail for individual buttons.
- Joystick data is returned as `f32`, which doesn't match `Motor::set_voltage`, making a cast necessary to spin motors (the most common operation done with controller data).
- We need some sort of event loop system for detecting press/release.

## Solutions

I think it might be worth considering returning all controller state as a single struct like `pros-rs` used to do:

```rs
let state = controller.state()?;

for motor in self.left_motors.iter_mut() {
    motor.set_voltage(state.left_stick.y * Motor::MAX_VOLTAGE)?;
}
for motor in self.right_motors.iter_mut() {
    motor.set_voltage(state.right_stick.y * Motor::MAX_VOLTAGE)?;
}
```

Although i'm still debating on whether or not this is a good idea. I think other rust libraries for gamepad/controller support have a similar scheme, so it's really tempting. No other device really does this though.

I also drafted up a system for reading controller press/release events in the driver loop before:

```rs
loop {
    match state.button_a.event() {
        Some(ButtonEvent::Press) => self.solenoid.open().ok(),
        Some(ButtonEvent::Release) => self.solenoid.close().ok(),
        _ => ()
    }

    sleep(Controller::UPDATE_INTERVAL).await;
}
```

**Comment by Aztro-dev** [comment]
Why does `Motor::set_voltage` even require double precision anyway? There's no way that a motor can respond to nanovolt differences.

**Comment by Tropix126** [comment]
> Why does `Motor::set_voltage` even require double precision anyway? There's no way that a motor can respond to nanovolt differences.

The SDK internally expects a `double` with `vexDeviceMotorVoltageSet`. That and general API consistency (most floating-point device methods in the SDK are double-precision).

**Comment by Gavin-Niederman** [comment]
> No other device really does this though.
Distance also does this. Regardless, I think returning all controller state at one time is a better API.
