### ISSUE TITLE
ADI error inconsistencies

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#159]
## Problem Description

Some ADI device error enums include `PortError`s under the `Adi` variant (e.g. addrled), while others have them under the `Port` variant (e.g. encoders). We should choose a variant name and be consistent with it.

**Comment by Tropix126** [comment]
I think we might want to revisit device error handling to an extent in general. Most notably
- Fallible device construction will eat up your port.
- There is a general lack of consistency with most errors.
- Double-check that Snafu is still the best choice for us here.
