### ISSUE TITLE
`LinkError::NonTerminatingNul` is a misnomer

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#169]
## Problem Description
`LinkError::NonTerminatingNul` implies that there may be a NUL byte in the terminating position, but this error is, in fact, returned if there is a NUL byte _anywhere_ in the ID string.

**Comment by Tropix126** [comment]
I actually might have some thoughts on these errors. We should maybe store the `NulError` in the variant and make it transparent (or whatever snafu's equivalent to that is), and just have a `NulError(NulError)` variant or similar.
