### ISSUE TITLE
`dbg!();` is broken.

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#173]
## Problem Description
The `dbg` macro does not compile unless there are parameters passed into it.

```rs
#![no_main]
#![no_std]

use vexide::prelude::*;

#[vexide::main]
async fn main(_peripherals: Peripherals) {
    dbg!();
}
```

**Comment by zabackary** [comment]
It looks like there's a typo in the macro definition. I'll start working on a PR now.
