### ISSUE TITLE
vexide no longer builds on non-ARM targets

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#192]
## Bug Description
A recent vex-sdk update broke support for non-VEX targets. 

## Code to reproduce
```
cargo v5 build -s --example basic
```

## Expected vs. actual behavior
This should either be fixed or listed as a breaking change.

## Additional information
IMO we should try and keep vexide somewhat untied to the armv7a architecture to make it easier for users to implement things like unit tests that run on the host.

**Comment by Tropix126** [comment]
This will hopfully be fixed by https://github.com/rust-lang/rust/pull/131530 which will allow us to specify `extern "system"` for VEXos syscalls.
