### ISSUE TITLE
Driver control doesn't start without competition hub

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#29]
## Bug Description
When testing locally without a competition happening, my driver control code never starts.

## Code to reproduce
TODO, I'll come back to this later once I make a minimum reproducible sample

## Expected vs. actual behavior
Operator control code should run even if the robot is not at a competition. In reality it never starts.

## Additional information
- I don't have access to a competition hub so it's possible that driver control code never runs whatsoever.

**Comment by Tropix126** [comment]
From testing previously, driver *did* run when on competition control, so this is likely due to some unnecessary check for the `CONNECTED` status flag.
