### ISSUE TITLE
Doesn't compile without critical_section feature

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#32]
## Bug Description
Disabling the critical_section feature makes the crate not compile.

## Code to reproduce
N/A

## Expected vs. actual behavior
There shouldn't be any broken features.

## Additional information
- I have tested this issue on the latest development release.
- Rust version (see `rustc --version`): rustc 1.78.0-nightly (256b6fb19 2024-02-06)
- vexide version (see `Cargo.toml`): 273c7bffa9945d6d89c1321c3ae19a71279fe33d

**Comment by Tropix126** [comment]
I think we should just remove the feature and just make this mandatory, since it's a critical part (pun intended) of our mutex implementation.

**Comment by Gavin-Niederman** [comment]
> I think we should just remove the feature and just make this mandatory, since it's a critical part (queue laugh track) of our mutex implementation.

I agree; this was only ever a feature because it wasn't used internally.
