### ISSUE TITLE
Add way to set text background color

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#69]
## What's the motivation for this feature?
It would be nice to set a background color when drawing Text to the screen. This way I can make my text a little more stylish, maybe improve contrast with dark foregrounds, etc.

## Describe the solution you'd like
One solution would be to add another method to Text that also takes `background` parameter (e.g. `Text::write`). Then, the Fill implementation would delegate out to that and choose a default background color.

Example:
```rs
let text = Text::new("Hello world", TextSize::Medium, (0, 0));
text.write(&mut screen, Rgb::WHITE, Rgb::BLACK);
```

## Describe the drawbacks, if any
This would mean you have to use a different method than other widgets to drawing Texts with backgrounds.

## Describe the alternative solutions, if any
Another option would be to add another parameter to the Fill trait.

## Additional context
The implementation should use `vexDisplayBackgroundColor` to set a background color before drawing text.

**Comment by zabackary** [comment]
I'm going to go ahead and implement this with the solution you proposed, even though it's probably true that there's a more elegant solution. Maybe there should be another trait `FillText` which implements a `fill_text` method specifically for `Text` widgets?

**Comment by zabackary** [comment]
Should there be a `fill_text` method on `Display` which takes `Text`, a foreground color, and background color?

**Comment by doinkythederp** [comment]
I think that would be the best option, and would advocate for calling it `Display::write` which is a little more concise.

**Comment by zabackary** [comment]
@Gavin-Niederman [mentioned](https://github.com/vexide/vexide/pull/247#pullrequestreview-2454937834) as a review comment that `write` might be a little ambiguous since it's completely unrelated to `vexide_core::io::Write::write`, so what do you think?

**Comment by zabackary** [comment]
Also, should `Text` even implement `Fill` to begin with?
