### ISSUE TITLE
Make widget properties gettable/settable or public

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#71]
## What's the motivation for this feature?
It's difficult for users to make extension traits around or to inspect widgets like `Circle`, `Line`, `Rect`, and `Text` because none of their properties are public, gettable, or settable. Most widgets are very uncomplicated and just hold data so I don't see any reason for their properties to be private.

## Describe the solution you'd like
All properties of `Circle`, `Line`, `Rect`, and `Text` should be `pub`.

## Describe the drawbacks, if any

The main drawback of this is that it will make updates to the internals of graphics widgets breaking changes to the crate. However, I don't really see them changing much outside of a large refactor.

## Describe the alternative solutions, if any

An alternative solution is to add getters (and setters) to widget structs.

## Additional context

N/A

**Comment by alexDickhans** [comment]
Can I get this one for my first issue?
