### ISSUE TITLE
Graphical panic messages do not appear in DoubleBuffered render mode

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#92]
## Bug Description

After using `Screen::set_render_mode` to set the render mode to `DoubleBuffered`, graphical panic messages will not appear and it will appear as if the program is frozen upon a panic.

## Code to reproduce

```rs
#![no_std]
#![no_main]

use vexide::prelude::*;

#[vexide::main]
async fn main(mut p: Peripherals) {
    p.screen.set_render_mode(vexide::devices::screen::RenderMode::DoubleBuffered);
    panic!("something failed");
}
```

## Expected vs. actual behavior

The panic message should appear on screen in a red box, but instead nothing appears at all.

## Additional information
- vexide version (see `Cargo.toml`): `259590b0e06c60b0662d5e871a25abbea4ff4984`
- I have tested this issue on the latest development release.
- I would be willing to implement a fix for this issue.
- Priority this issue should have (low/med/high): med
- This can be fixed by calling `vexDisplayRender` in the panic handler.

**Comment by alexDickhans** [comment]
From what I can tell this also happens with `Text` widgets

**Comment by doinkythederp** [comment]
> From what I can tell this also happens with `Text` widgets

What you're describing might actually be the intended behavior outside of a panic: the double buffered render mode switches the screen into a state where all drawing is delayed until `Screen::render` is called. When a panic occurs, the handler doesn't call `Screen::render` so the message is never displayed.
